### ISSUE TITLE
Publish to a maven repo

### ISSUE THREAD

**Issue by petedoyle** [petedoyle/android-support-v4-googlemaps#1]
It'd be nice to be able to pull in this library via Maven.

**Comment by kmerrell42** [comment]
I second that!

**Comment by raulraja** [comment]
Pete, there is way too many people using you library to not be available as a maven dependency. We @47deg are building also other Android libs where we plan on adding your library as a dependency for certain builds of our libraries that depend on FragmentActivity's but for those that use the FragmentMapActivity. It would be great if your lib was available as a snapshot in nexus sonatype and released in central. http://datumedge.blogspot.com.es/2012/05/publishing-from-github-to-maven-central.html 
Thanks for your consideration!

**Comment by vladson** [comment]
Yes, it will be great, if you consider to publish it for maven

**Comment by petedoyle** [comment]
Hi guys, sorry for never getting around to this.  Let me know if this is still useful now that Google has released a new Maps API with Fragment support:
http://android-developers.blogspot.com/2012/12/new-google-maps-android-api-now-part-of.html

**Comment by petedoyle** [comment]
Closing old issues. There are much better ways to use maps now. :)
