### ISSUE TITLE
Create separate FragmentMapActivity class

### ISSUE THREAD

**Issue by James-Robinson** [petedoyle/android-support-v4-googlemaps#10]
Since all classes extend FragmentActivity it is tricky to incorporate this modified support library such that it will work on devices without google maps. Introducing a separate FragmentMapActivity class would make this easier.

For example, consider an app using a tab layout with each tab being a fragment and one of those tabs holding a map. Using the current library the app would FC immediately on devices without  Google APIs (since every fragment has a reference to google maps).  If a FragmentMapActivity class were created and used this could be applied to only the tab holding the map, then reflection could be used at runtime and this map could be removed for devices without access to google APIs.

Great project!

**Comment by petedoyle** [comment]
Thanks James, your reasoning is 100% dead on. :+1:  Closing this since there's now official support for fragments from Google:
http://android-developers.blogspot.com/2012/12/new-google-maps-android-api-now-part-of.html
