### ISSUE TITLE
Upgrade to revision 11

### ISSUE THREAD

**Issue by will-quast** [petedoyle/android-support-v4-googlemaps#11]
There is a new revision of the Support Package, revision 11.
Everyone is excited to use nested Fragments. :)

Thanks a whole bunch, this jar really saves everyone from a huge headache.

**Comment by petedoyle** [comment]
Here's a preview if you feel like playing:

[android-support-v4-r11-googlemaps-SNAPSHOT-20121114-1811Z.jar](https://dl.dropbox.com/u/18509454/gh/android-support-v4-googlemaps/android-support-v4-r11-googlemaps-SNAPSHOT-20121114-1811Z.jar)
md5sum: 1b8d4733368563aba8af8a380596e614

[android-support-v13-r11-googlemaps-SNAPSHOT-20121114-1811Z.jar](https://dl.dropbox.com/u/18509454/gh/android-support-v4-googlemaps/android-support-v13-r11-googlemaps-SNAPSHOT-20121114-1811Z.jar)
md5sum: 6955de1b9e3a24f8632beb64a03bb406

These are basically releases but I haven't had a chance to test them in my apps yet.  Its just the stock Google r11 release plus this: 56f9306a01.

The official release might be a couple days away.  Gonna see if I can add maven support beforehand :)

**Comment by DoubleAA** [comment]
Hey i have been messing with the releases that you provided here. Works well for what i have tested it for. Mainly mixing google maps with nested fragments. Good work.

**Comment by petedoyle** [comment]
Thanks guys, r11 is finally out.  More importantly, (if you haven't heard), Google just released official Fragment support:
https://groups.google.com/forum/?fromgroups=#!topic/android-support-v4-googlemaps-support/g37pSuTG4E8
