### ISSUE TITLE
Android SDK Version 17

### ISSUE THREAD

**Issue by webmaster128** [petedoyle/android-support-v4-googlemaps#12]
- [android-sdk-path]/tools/android sdk
  Download "Android 4.2 (API 17) SDK Platform"
- git clone git://github.com/petedoyle/android-support-v4-googlemaps.git
- cd android-support-v4-googlemaps
- rm -r ./support/
- cp -R  [android-sdk-path]/extras/android/support/ ./
- cp  [android-sdk-path]/platforms/android-17/android.jar lib/android-17.jar
- rm ./lib/android-16.jar
- Apply: https://github.com/petedoyle/android-support-v4-googlemaps/commit/c8e271698e762c46cacf47fe10b3495122e75a69
- Replace
  `protected void onNewIntent(Intent intent) {`
  with
  `public void onNewIntent(Intent intent) {`
  in
    ./support/v4/src/java/android/support/v4/app/FragmentActivity.java
- Replace twice
          `<include name="jellybean/**/*.java"/>`
  with
            `<include name="jellybean/**/*.java"/>
            <include name="jellybean-mr1/**/*.java"/>`
  in
    ./build.xml
- ant

Make sure ant compiles with java 1.6. Check `javac -version`

Worked for me. Cheers

**Comment by petedoyle** [comment]
Thanks :) The r11 release is finally out.
