### ISSUE TITLE
Please undeprecate your library

### ISSUE THREAD

**Issue by ghost** [petedoyle/android-support-v4-googlemaps#13]
Google Maps API v2 is not ready for production. I attempted to integrate it into my application and found that really weird things happen when you switch back and forth between fragments with it, such as black screens and so on.

**Comment by will-quast** [comment]
http://stackoverflow.com/questions/13837697/viewpager-with-google-maps-api-v2-mysterious-black-view

**Comment by ghost** [comment]
@will, thanks, that's a great fix. Unfortunately, by the time I read it I'd already integrated pete's library + polaris and it's working swell :)

**Comment by will** [comment]
I have no idea what this is. Maybe you mean some other will

On Jan 25, 2013, at 6:01 PM, Tom Dignan notifications@github.com wrote:

@will https://github.com/will, thanks, that's a great fix. Unfortunately,
by the time I read it I'd already integrated pete's library + polaris and
it's working swell :)

—
Reply to this email directly or view it on
GitHubhttps://github.com/petedoyle/android-support-v4-googlemaps/issues/13#issuecomment-12729235.

**Comment by petedoyle** [comment]
Closing old issues. There are much better ways to use maps now. :)
