### ISSUE TITLE
Implement FragmentActivity without MapActivity

### ISSUE THREAD

**Issue by NightWatchman** [petedoyle/android-support-v4-googlemaps#4]
In regards to:

"Currently, one downside is that ALL classes extending FragmentActivity are MapActivitys. Its possible to make a separate class (i.e. FragmentMapActivity), but it requires some refactoring of the FragmentActivity code.

Feel free to file a bug to request it or fork this project to fix it."

I would love to see an implementation of this project that supports FragmentActivity(s) both with and without extending MapView.  Unfortunately Google's limitation of allowing only one MapActivity per process makes things quite awkward.  Effectively I can only have one FragmentActivity per process.

I can't include both the Compatibility package from Google and this one because they share the same namespaces.

**Comment by 9re** [comment]
I've implemented Fragment and FragmentManager not to depend on FragmentActivity.
I split methods to FragmentActivityFeature interface.
Now you can use Fragments in your own Activity with FragmentActivityFeature.
For detail, please see the diff.

https://github.com/9re/android-support-v4-googlemaps/tree/experimental-fragment-activity-feature-impl

**Comment by NightWatchman** [comment]
I gave it a shot, but I can't build it against Google API Level 7 since android.view.View.AccessibilityDelegate didn't exist until Android API level 14.  I tried to build it against Google API level 14 and I got an error:

trouble processing "javax/xml/transform/dom/DOMLocator.class":
Ill-advised or mistaken usage of a core class (java.\* or javax.*)

I'm not really sure how to incorporate your revisions in to my project or build a jar file from your source.  I'm currently using the pre-compiled release android-support-v4-r4-googlemaps.jar in my project.

**Comment by 9re** [comment]
I'm using this project with Google API Level 4.

・First, build the project with API level 14 and make the jar.
・Then, use the jar in your project.

you can make the jar with ant or eclipse.

$ git clone git://github.com/9re/android-support-v4-googlemaps.git
$ cd android-support-v4-googlemaps
$ git checkout experimental-fragment-activity-feature-impl
$ ant

if you fail to build, then you must be using older versions of jdk6.
you should see compiler errors discribed here:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=98379

in this case, you can choose three ways:
・use jdk 7 and target to java 6
・use eclipse to build the jar
・use patch for jdk 6
$ patch -p1 < for-jdk-6.patch
$ ant

using this patch, you'll always have to cast to ActivityFragmentFeature to use support package apis:
Activity activity = getActivity();
ActivityFragmentFeature feature = (ActivityFragmentFeature) activity;
FragmentManager manager = feature.getSupportFragmentManager();

i'm preparing a blog entry to describe my implementation in detail and will publish it in a few days!

**Comment by NightWatchman** [comment]
I was able to build your new implementation and I'm using it in my project.  It's working great so far!  It took me a second to figure out you implemented a FragmentMapActivity and a FragmentActivity but I think I've got everything sorted now.  Great job on this project, it's much appreciated!
