### ISSUE TITLE
creating jar with source attached

### ISSUE THREAD

**Issue by shayerov** [petedoyle/android-support-v4-googlemaps#7]
Hi,
Can you please create the jars with source attached for downloading? It helps a lot when trying to debug errors in the application.
The new ADT for Eclipse does not let me attach sources to the jar since it's part of the "Android dependency" now.

Thank you very much!
 Shay

**Comment by petedoyle** [comment]
Sorry I never got around to this.  Closing now that Google has added Fragment support:
https://groups.google.com/forum/?fromgroups=#!topic/android-support-v4-googlemaps-support/g37pSuTG4E8
